# -*- coding: utf-8 -*-
"""AtlasModels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121awpkKdOpfpOf8GCpbXomwO6On4EoIO

# Loading and Processing Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.feature_selection import VarianceThreshold
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, mean_squared_error, r2_score


# loading daatsets
datapaths = ['https://raw.githubusercontent.com/RyanDux03/AtlasGDP/main/data/historical data/ARE_data.csv',
             'https://raw.githubusercontent.com/RyanDux03/AtlasGDP/main/data/historical data/CHN_data.csv',
             'https://raw.githubusercontent.com/RyanDux03/AtlasGDP/main/data/historical data/DEU_data.csv',
             'https://raw.githubusercontent.com/RyanDux03/AtlasGDP/main/data/historical data/IND_data.csv',
             'https://raw.githubusercontent.com/RyanDux03/AtlasGDP/main/data/historical data/USA_data.csv']

names = ['ARE', 'CHN', 'DEU', 'IND', 'USA']

data = []
for path in datapaths:
    data.append(pd.read_csv(path))


test_train_data = []
fitted_transformers = [] # To store fitted transformers for each country

# Global SMOTE instance (if used, it does not need to be refitted per country)
smote = SMOTE(random_state=42)

def prepare_xy_with_transformers(country_data):
  # Instantiate transformers locally for each country to ensure independent fitting
  scalar = StandardScaler()
  imputer = SimpleImputer(strategy='constant', fill_value=0)
  selector = VarianceThreshold(threshold=0.01)

  # Keep 'Year' as a feature, drop only 'Country' and 'gdp_usd'
  x = country_data.drop(columns=['Country', 'gdp_usd'])
  y = country_data.gdp_usd

  # Identify categorical columns for Label Encoding (excluding 'Year' which is numeric)
  categorical_cols = x.select_dtypes(include=['object']).columns
  for col in categorical_cols:
    # Using a new LabelEncoder for each categorical column
    le = LabelEncoder()
    x[col] = le.fit_transform(x[col])

  # Impute missing values
  x_imputed = pd.DataFrame(imputer.fit_transform(x), columns=x.columns)

  # Feature Selection - Removing low variance features
  # Store column names before selection to map back correctly
  pre_selection_columns = x_imputed.columns
  x_selected_array = selector.fit_transform(x_imputed)

  # Get the names of features that were kept by the selector
  selected_feature_indices = selector.get_support(indices=True)
  selected_feature_names = pre_selection_columns[selected_feature_indices]
  x_selected = pd.DataFrame(x_selected_array, columns=selected_feature_names)

  # Check if SMOTE is possible and apply
  unique, counts = np.unique(y, return_counts=True)
  if np.all(counts > 1):
    x_balanced, y_balanced = smote.fit_resample(x_selected, y)
  else:
    x_balanced, y_balanced = x_selected, y

  # Feature Scaling (Z-score normalization)
  x_scaled = pd.DataFrame(scalar.fit_transform(x_balanced), columns=x_balanced.columns)

  # Return processed data and the fitted transformers for later use
  return x_scaled, y_balanced, scalar, imputer, selector


for i, (country_data) in enumerate(data):
    # Pass country_data.iloc[:-1] for training, as before
    x, y, scalar_fit, imputer_fit, selector_fit = prepare_xy_with_transformers(country_data.iloc[:-1])

    # Splitting the dataset into train/test data
    x_train, x_test, y_train, y_test = train_test_split(x,
                                                        y,
                                                        test_size=0.2,
                                                        random_state=42)

    test_train_data.append((names[i],
                              country_data, # Original country_data (full) for reference in future pred
                              x_train, x_test, y_train, y_test))
    fitted_transformers.append((scalar_fit, imputer_fit, selector_fit))

"""#Random Forest Models"""

# random forest models

random_forest_models = []

for country_name, country_data, x_train, x_test, y_train, y_test in test_train_data:
  rf = RandomForestRegressor(random_state=42)

  rf.fit(x_train, y_train)

  random_forest_models.append(rf)

  y_pred = rf.predict(x_test)

  mse = mean_squared_error(y_test, y_pred)
  r2 = r2_score(y_test, y_pred)

  print(f"Mean Squared Error for {country_name}: {mse}")
  print(f"R-squared for {country_name}: {r2}")

  plt.figure(figsize=(10, 6))
  plt.scatter(x_test.Year, y_pred)
  plt.xlabel('Year')
  plt.ylabel('Predicted Values')
  plt.title(f'Year Vs. Predicted Values for {country_name}, Random Forest')
  plt.grid(True)
  plt.plot
  plt.show()

"""# Linear Models"""

linear_models = []

for country_name, country_data, x_train, x_test, y_train, y_test in test_train_data:

  # Train Linear Regression model
  lr = LinearRegression()
  lr.fit(x_train, y_train)
  linear_models.append(lr)

  # Get predictions from Linear Regression
  lr_pred = lr.predict(x_test)

  # Evaluate hybrid model
  mse_lr = mean_squared_error(y_test, lr_pred)
  r2_lr = r2_score(y_test, lr_pred)

  print(f"\nLinear Model Metrics for {country_name}:")
  print(f"Mean Squared Error: {mse_lr}")
  print(f"R-squared: {r2_lr}")

  # Plotting Actual vs. Predicted for Linear Model
  plt.figure(figsize=(10, 6))
  plt.scatter(x_test.Year, lr_pred, alpha=0.7)
  plt.xlabel('Year')
  plt.ylabel('Predicted Values')
  plt.title(f'Year vs. Predicted Values for Linear Model - {country_name}')
  plt.grid(True)
  plt.show()

"""# Hybrid Models"""

stacked_hybrid_models = []
hybrid_country_accuracies = []

for i, (country_name, country_data, x_train, x_test, y_train, y_test) in enumerate(test_train_data):

  # Retrieve the pre-trained Linear Regression model
  lr = linear_models[i]

  ada_boost = AdaBoostRegressor(estimator=lr,
                              n_estimators=50,
                              learning_rate=0.1)

  parameters_boost = {'n_estimators': [100, 200, 300]}

  # Searching the hyper-parameters
  clf_boost = GridSearchCV(ada_boost, parameters_boost, n_jobs=-1)
]
  clf_boost.fit(x_train, y_train)

  hybrid_pred_test = clf_boost.predict(x_test)

  # Store the list of models for this country
  stacked_hybrid_models.append(clf_boost)

  # Calculate the Mean Squared Error (mse_hybrid) and R-squared score (r2_hybrid)
  mse_hybrid = mean_squared_error(y_test, hybrid_pred_test)
  r2_hybrid = r2_score(y_test, hybrid_pred_test)

  # Print the country name, the calculated mse_hybrid, and r2_hybrid
  print(f"\nBoosted Hybrid Model Metrics for {country_name}:")
  print(f"Mean Squared Error: {mse_hybrid}")
  print(f"R-squared: {r2_hybrid}")

  # Create a scatter plot of y_test (Actual Values) against hybrid_pred_test (Predicted Values)
  plt.figure(figsize=(10, 6))
  plt.scatter(x_test.Year, hybrid_pred_test, alpha=0.7) # Use x_test.Year directly
  plt.xlabel('Year')
  plt.ylabel('Predicted Values')
  plt.title(f'Year vs. Predicted Values for Boosted Hybrid Model - {country_name}, (Stages: 50, LR: 0.1)')
  plt.grid(True)
  plt.show()

"""# Predictions Forecast"""

def prepare_future_data(models):

  all_country_predictions_dfs = []
  country_accuracies = []

  for i, (country_name, initial_country_data, x_train_original, x_test_original, y_train_original, y_test_original) in enumerate(test_train_data):
      scalar_fit, imputer_fit, selector_fit = fitted_transformers[i]
      model = models[i]

      # --- Step 1: Pre-process initial_country_data for consistent Label Encoding ---
      # Create a copy to avoid modifying the original DataFrame which might be used elsewhere
      processed_initial_country_data = initial_country_data.copy()

      # Identify categorical columns (excluding 'Year' and 'gdp_usd')
      categorical_cols = processed_initial_country_data.select_dtypes(include=['object']).columns.drop('Country', errors='ignore')

      # Store LabelEncoders for each categorical column for later use with future data
      country_label_encoders = {}
      for col in categorical_cols:
          le = LabelEncoder()
          # Fit and transform on the historical data
          processed_initial_country_data[col] = le.fit_transform(processed_initial_country_data[col])
          country_label_encoders[col] = le

      # Separate features (X) and target (Y) from the now label-encoded historical data
      x_historical_le = processed_initial_country_data.drop(columns=['Country', 'gdp_usd'])
      y_historical = processed_initial_country_data['gdp_usd']


      # --- Future Predictions (FIXED WITH TREND EXTRAPOLATION) ---
      last_year_in_historical_data = x_historical_le['Year'].max()
      future_years = [last_year_in_historical_data + j for j in range(1, 6)]

      # Prepare future feature rows using extrapolation based on original raw data first
      features_for_extrapolation = initial_country_data.drop(columns=['Country', 'gdp_usd']).copy()
      future_rows = []

      for future_year in future_years:
          future_row_dict = {}
          for col in features_for_extrapolation.columns:
              if col == 'Year':
                  future_row_dict[col] = future_year
              else:
                  if features_for_extrapolation[col].dtype in ['int64', 'float64']:
                      last_5_values = features_for_extrapolation[col].tail(5).values
                      if len(last_5_values) >= 2:
                          trend = last_5_values[-1] - last_5_values[0]
                          trend_per_year = trend / (len(last_5_values) - 1)
                          years_ahead = future_year - last_year_in_historical_data
                          future_row_dict[col] = last_5_values[-1] + (trend_per_year * years_ahead)
                      else:
                          future_row_dict[col] = features_for_extrapolation[col].iloc[-1]
                  else: # Categorical column
                      future_row_dict[col] = features_for_extrapolation[col].iloc[-1] # Use last known value as string

          future_rows.append(future_row_dict)

      x_future_raw = pd.DataFrame(future_rows)

      # Apply LabelEncoding to future data using the fitted encoders
      for col in categorical_cols:
          if col in x_future_raw.columns:
              # Use .loc for setting values to avoid SettingWithCopyWarning
              x_future_raw.loc[:, col] = country_label_encoders[col].transform(x_future_raw[col])

      # Apply Imputer, Selector, Scaler to future data
      x_future_imputed = pd.DataFrame(imputer_fit.transform(x_future_raw), columns=x_future_raw.columns)
      x_future_selected_np = selector_fit.transform(x_future_imputed)
      model_feature_names = x_train_original.columns # Feature names after selector during original training

      # Ensure that the columns of x_future_processed_df match model_feature_names in order and presence
      x_future_processed_df = pd.DataFrame(x_future_selected_np, columns=model_feature_names)
      x_future_scaled_np = scalar_fit.transform(x_future_processed_df) # Scale the selected features
      x_future_processed_df = pd.DataFrame(x_future_scaled_np, columns=model_feature_names)

      y_future = model.predict(x_future_processed_df)

      future_df = pd.DataFrame({
          "country": country_name,
          "year": future_years,
          "actual_gdp": np.nan,
          "predicted_gdp": y_future,
          "is_test": 0,
          "is_forecast": 1
      })

      # --- Create new time-based test_df and train_df ---
      all_years = x_historical_le['Year'].sort_values().unique()
      if len(all_years) >= 5:
          test_years_new = all_years[-5:]
          train_years_new = all_years[:-5]
      else: # If less than 5 years, treat all as test
          test_years_new = all_years
          train_years_new = []

      # Filter the label-encoded historical features (x_historical_le) and target (y_historical)
      x_test_new_le = x_historical_le[x_historical_le['Year'].isin(test_years_new)].copy()
      y_test_new_actual = y_historical[x_historical_le['Year'].isin(test_years_new)].copy()

      x_train_new_le = x_historical_le[x_historical_le['Year'].isin(train_years_new)].copy()
      y_train_new_actual = y_historical[x_historical_le['Year'].isin(train_years_new)].copy()

      # Apply Imputer, Selector, Scaler from `fitted_transformers`
      # Transform the new time-based test data
      x_test_new_imputed = pd.DataFrame(imputer_fit.transform(x_test_new_le), columns=x_test_new_le.columns)
      x_test_new_selected_np = selector_fit.transform(x_test_new_imputed)
      x_test_new_processed_df = pd.DataFrame(x_test_new_selected_np, columns=model_feature_names) # Use model's feature names
      x_test_new_scaled_np = scalar_fit.transform(x_test_new_processed_df) # Scale the selected features
      x_test_new_processed_df = pd.DataFrame(x_test_new_scaled_np, columns=model_feature_names)


      # Transform the new time-based train data (only if there is train data)
      if not x_train_new_le.empty:
          x_train_new_imputed = pd.DataFrame(imputer_fit.transform(x_train_new_le), columns=x_train_new_le.columns)
          x_train_new_selected_np = selector_fit.transform(x_train_new_imputed)
          x_train_new_processed_df = pd.DataFrame(x_train_new_selected_np, columns=model_feature_names) # Use model's feature names
          x_train_new_scaled_np = scalar_fit.transform(x_train_new_processed_df) # Scale the selected features
          x_train_new_processed_df = pd.DataFrame(x_train_new_scaled_np, columns=model_feature_names)
          y_train_new_pred = model.predict(x_train_new_processed_df)
      else:
          x_train_new_processed_df = pd.DataFrame(columns=model_feature_names) # Empty DataFrame
          y_train_new_pred = np.array([]) # Empty array


      # Make predictions using the already trained model
      y_test_new_pred = model.predict(x_test_new_processed_df)


      test_df = pd.DataFrame({
          "country": country_name,
          "year": test_years_new,
          "actual_gdp": np.nan,
          "predicted_gdp": y_test_new_pred,
          "is_test": 1,
          "is_forecast": 0
      })

      train_df = pd.DataFrame({
          "country": country_name,
          "year": train_years_new,
          "actual_gdp": y_train_new_actual.values if not y_train_new_actual.empty else np.array([]),
          "predicted_gdp": np.nan,
          "is_test": 0,
          "is_forecast": 0
      })

      # Concatenate all three dataframes for the current country
      country_combined_df = pd.concat([train_df, test_df, future_df], ignore_index=True)
      country_combined_df = country_combined_df.sort_values(by='year')
      all_country_predictions_dfs.append(country_combined_df)

      y_test_r2 = pd.concat([y_train_new_actual, y_test_new_actual])
      y_pred_r2 = np.concatenate([y_train_new_pred, y_test_new_pred])

      # Calculate R-squared
      r2_score_value = r2_score(y_test_r2, y_pred_r2)
      country_accuracies.append((country_name, r2_score_value))

      '''# plot predicted years
      plt.figure(figsize=(10, 6))
      plt.scatter(country_combined_df['year'], country_combined_df['predicted_gdp'], label='Future Predictions', color='blue')
      plt.xlabel('Year')
      plt.ylabel('Predicted GDP')
      plt.title(f'Predicted GDP for {country_name} Future Years')
      plt.legend()
      plt.grid(True)
      plt.show()'''

  final_all_country_predictions = pd.concat(all_country_predictions_dfs, ignore_index=True)
  return final_all_country_predictions, country_accuracies

df_rf_predictions, rf_country_accuracies = prepare_future_data(random_forest_models)
df_lr_predictions, lr_country_accuracies = prepare_future_data(linear_models)
df_hybrid_predictions, hybrid_country_accuracies = prepare_future_data(stacked_hybrid_models)

df_rf_predictions.to_csv('rf_predictions.csv', index=False)
df_lr_predictions.to_csv('lr_predictions.csv', index=False)
df_hybrid_predictions.to_csv('hybrid_predictions.csv', index=False)

"""# Plots"""

# plot predictions

plt.figure(figsize=(10, 6))
sns.lineplot(data=df_rf_predictions, x='year', y='predicted_gdp', hue='country', palette='tab10')
plt.xlabel('Year')
plt.ylabel('Predicted GDP')
plt.grid(True)
plt.title('Predicted GDP for Random Forest Models')
plt.show()

plt.figure(figsize=(10, 6))
sns.lineplot(data=df_lr_predictions, x='year', y='predicted_gdp', hue='country', palette='tab10')
plt.xlabel('Year')
plt.ylabel('Predicted GDP')
plt.grid(True)
plt.title('Predicted GDP for Linear Regression Models')
plt.show()

plt.figure(figsize=(10, 6))
sns.lineplot(data=df_hybrid_predictions, x='year', y='predicted_gdp', hue='country', palette='tab10')
plt.xlabel('Year')
plt.ylabel('Predicted GDP')
plt.grid(True)
plt.title('Predicted GDP for Hybrid Models')
plt.show()

"""# Print Accuracies"""

for acc in rf_country_accuracies:
  print(f"RF: R^2 = {acc[1]}, Country = {acc[0]}")

for acc in hybrid_country_accuracies:
  print(f"Hybrid: R^2 = {acc[1]}, Country = {acc[0]}")